### ISSUE TITLE
Where does gxpkgd live?

### ISSUE THREAD

**Issue by belmarca** [vyzo/gxpkg-daemon#3]
https://github.com/vyzo/gxpkg-daemon/blob/486ce85e6901f0eb813c974fe2511a9eb9cf1219/gerbil.pkg#L1

Do you want to import it using `:vyzo/gxpkg/gxpkg-daemon` or with either of `:vyzo/gxpkgd` and `:vyzo/gxpkg-daemon`?

**Comment by vyzo** [comment]
`gxkpgd` is a binary, it gets installed in `GERBIL_PATH/bin` when the package is built.

So you don't normally import it, you run it!
The module of the binary is `:vyzo/gxpkg/gxpkgd` in case you want to have it export a wider interface for scripting.

**Comment by vyzo** [comment]
Perhaps the package should be `:vyzo/gxpkgd` however (in case the module would become `:vyzo/gxpkgd/gxpkgd`).
